/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string>;

export interface ImageRequests {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  link: string | null;
  submitted_forms_ids: Int8 | null;
}

export interface Path {
  path: Generated<Int8>;
}

export interface PathMetadata {
  cycle: number | null;
  date: Timestamp;
  id: Generated<string>;
  path: Int8 | null;
  satellite: string | null;
}

export interface SubmittedForms {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  latitude: number;
  lead_time: Int8 | null;
  longitude: number;
  max_cloud_cover: number | null;
  name: string | null;
  span_end_time: Timestamp | null;
  span_start_time: Timestamp | null;
  type: string | null;
  updated_at: Timestamp | null;
}

export interface DB {
  image_requests: ImageRequests;
  path: Path;
  path_metadata: PathMetadata;
  submitted_forms: SubmittedForms;
}
